Final_App_ManageImages/config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'
  root 'welcome#index'

  devise_for :users
  devise_scope :user do
  root to: "devise/sessions#new"
end
	resources :users

  resources :albums

  resources :pictures
 
end

Final_App_ManageImages/app/models/album.rb
class Album < ApplicationRecord

	has_many :pictures, dependent: :destroy
	
end

Final_App_ManageImages/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Final_App_ManageImages/app/models/picture.rb
class Picture < ApplicationRecord
	
	belongs_to :album, counter_cache: true
	belongs_to :user
	
	has_attached_file :image, styles: {large: "600x600>", medium: "300x300>", thumb: "150x150>"}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

	validates :title, presence: true
	validates :description, presence: true
	validates :is_public, inclusion: { in: [true, false] }

	scope :publics, -> {where(is_public: true) }
end

Final_App_ManageImages/app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pictures
  has_many :albums, dependent: :destroy

end

Final_App_ManageImages/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)
    
    respond_to do |format|
      if @album.save

        if params[:image]
        params[:image].each { |image|
          @albums.pictures.create(image: image)
        }
      end

        format.html { redirect_to @album, notice: I18n.t('.noticed_create') }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: I18n.t('.noticed_update') }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: I18n.t('.noticed_destroy') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:name, :description, :is_public, :image)
    end
end

Final_App_ManageImages/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    pictures_path
  end

end

Final_App_ManageImages/app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_picture, only: [:show, :edit, :update, :destroy]
  #index  

  def index 

    @pictures = Picture.publics.order("created_at DESC").page(params[:page]).per_page(6)
  
  end

  #show
  def show 

  end 

  #new 
  def new
    @picture = Picture.new
  end 


  #create
  def create
    @picture = Picture.new(picture_params)

    if @picture.save
      flash[:notice] = t(:noticed_success_create)
      redirect_to @picture
    else
      render 'new'
      flash[:notice] = t(:noticed_fail_create)
    end
  end

  #edit 
  def edit 


  end 

  #update
  def update
    if @picture.update(picture_params)
      flash[:notice] = t(:noticed_success_update)
      redirect_to @picture
    else
      render 'edit'
      flash[:notice] = t(:noticed_fail_update)
    end 
  end 
  
  # destroy
  def destroy
    @picture.destroy
    flash[:notice] = t(:noticed_destroy)
    redirect_to pictures_path
  end

  private

  def find_picture
    @picture = Picture.find(params[:id])
  end

  def picture_params
    params.require(:picture).permit(:title, :description, :image, :user_id, :is_public)
  end

end

Final_App_ManageImages/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user, only: [:show, :edit, :update, :destroy]


def index

	@user = User.all
end


def new 
	@user = User.new
end


def show 
	@user = User.find(params[:id])
end


def create
	@user = User.new(user_params)
	if @user.save
		redirect_to @user.save
	else
		render 'new'
end


def update 

end


def destroy
	
end


  private

    def find_user
      @user = User.find(params[:id])
    end

    def user_params
		params.require(:user).permit(:username, :email, :password)
	end
end

end

Final_App_ManageImages/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	 before_action :authenticate_user!
  
def index
    redirect_to pictures_path if user_signed_in?
  end
  
end

Final_App_ManageImages/app/helpers/albums_helper.rb
module AlbumsHelper
end

Final_App_ManageImages/app/helpers/anbums_helper.rb
module AnbumsHelper
end

Final_App_ManageImages/app/helpers/application_helper.rb
module ApplicationHelper
end

Final_App_ManageImages/app/helpers/pictures_helper.rb
module PicturesHelper
end

Final_App_ManageImages/app/helpers/users_helper.rb
module UsersHelper
end

Final_App_ManageImages/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Final_App_ManageImages/app/views/albums/_form.html.haml
= form_for(@album, html: {multipart: true}) do |f|

	= f.label :pictures
	= file_field_tag "images[]", class: "btn", multiple: true

	= f.hidden_field :user_id, :value => current_user.id
	= f.label I18n.t('name abums')
	= f.text_area :name, class: "form-control"
	<br>

	= f.label I18n.t('description')
	= f.text_area :description, class: "form-control"
	<br>

	= f.check_box :is_public
	= f.label I18n.t('public album')
	<br>
	<br>
	= f.submit I18n.t('submit') , class: "btn btn-info"

Final_App_ManageImages/app/views/albums/edit.html.haml
.edit-album
	%h1 EDITING ALBUM

	= render 'form'

	= link_to t('.edit'), @album
	\|
	= link_to t('.back'), albums_path

Final_App_ManageImages/app/views/albums/index.html.haml
.listing-album 
  %h1 #{I18n.t('listing_album')}

  %table.table.table-hover.table-responsive.show-empty-cells
    %thead

      %tr
        %th #{I18n.t('name')}
        %th #{I18n.t('description')}
        %th #{I18n.t('public')}
        %th
        %th
        %th
        %thead

    %tbody
      - @albums.each do |album|
        %tr
          %td= album.name
          %td= album.description
          %td= album.is_public
          %td= link_to t('.show'), album, class: "btn btn-success"
          %td= link_to t('.edit'), edit_album_path(album), class: "btn btn-info"
          %td= link_to t('.destroy'), album, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"

  %br
.wraping-new-cancel
  = link_to t('.new_album'), new_album_path, class: "btn btn-info"
  = link_to t('.cancel'), pictures_path, class: "btn btn-info"

Final_App_ManageImages/app/views/albums/new.html.haml
.form-new-album

	%h1 #{I18n.t('new_album')}

	= render 'form'

	= link_to t('.back'), albums_path

Final_App_ManageImages/app/views/albums/show.html.haml
.detail-album
	%h1 #{I18n.t('detail_album')}
	%p#notice= notice

	%p
	%b #{I18n.t('name')}
	= @album.name
	%p 	
	<br>
	%b #{I18n.t('description')}
	= @album.description
	%p
	<br>
	%b #{I18n.t('public')}
	= @album.is_public
	<br>
	<br>
	%b Pictures:

	<br>
	<br>
	<br>
	= link_to I18n.t('edit'), edit_album_path(@album), class: "btn btn-info"

	= link_to I18n.t('back'), albums_path, class: "btn btn-info"

Final_App_ManageImages/app/views/layouts/application.html.haml
%html
%head
  %title Manage Images | Final App
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  %link{:rel => "stylesheet", :href => "path/to/font-awesome/css/font-awesome.min.css"}/
  = csrf_meta_tags
  %br/

.header   
  - if user_signed_in?
    %i.glyphicon.glyphicon-camera
    = link_to t('.sign_out'), destroy_user_session_path, method: :delete, class: "navbar-text navbar-right"
    = link_to t('.new_picture'), new_picture_path, class: "navbar-text navbar-right"
    = link_to t('.all_pictures') ,pictures_path, class: "navbar-text navbar-right"
    = link_to t('.new_album'), new_album_path, class: "navbar-text navbar-right"
    
  - else
    = link_to I18n.t('login'), new_user_session_path
  %p.notice= notice
  %p.alert= alert
.img  


  = yield

Final_App_ManageImages/app/views/pictures/_form.html.haml
= form_for(@picture, html: {multipart: true}) do |f|

  = f.hidden_field :album_id, value: user.id
  
  = f.label I18n.t('image')
  = f.file_field :image
  <br>
  
  = f.label I18n.t('title')
  = f.text_field :title, class: "form-control"
  <br>

  = f.label I18n.t('description')
  = f.text_area :description, class: "form-control"
  <br>

  = f.check_box :is_public
  =f.label I18n.t('public image')
  <br> <br>

  = f.submit I18n.t('submit') , class: "btn btn-info"
  

Final_App_ManageImages/app/views/pictures/edit.html.haml
.center
	%h1 #{I18n.t('edit_picture')}
	<br>
	= render 'form',  user: current_user
	= link_to I18n.t('cancel'), pictures_path

Final_App_ManageImages/app/views/pictures/form.html.haml
=form_for @picture do |p|
	=p.input :title 
	=p.input :description
	=p.button :submit

Final_App_ManageImages/app/views/pictures/index.html.haml
.padding
  - if @pictures.present?
    - @pictures.each do |picture|
      
      %a{ href: (url_for [picture])}
      .body
        = link_to image_tag picture.image.url(:thumb)
        %h4.title= link_to picture.title, picture
        %h5.date= time_ago_in_words(picture.created_at)
  - else
    %h2 #{I18n.t('add_picture')}
    %button= link_to t('.new_picture'), new_picture_path

.will-page
  = will_paginate @picture, renderer: BootstrapPagination::Rails

Final_App_ManageImages/app/views/pictures/new.html.haml
.wrapper
	%h1 #{I18n.t('add_picture')}
	=render 'form', user: current_user
	= link_to I18n.t('cancel'), pictures_path

Final_App_ManageImages/app/views/pictures/show.html.haml
.center-detail
	%h1 #{I18n.t('detail_picture')}
	<br>
	= image_tag @picture.image.url(:large) 
	%h2.title=@picture.title 
	%p.description= @picture.description

<br>
.buttons
	= link_to (t'.all_picture'), pictures_path, class: "btn btn-info"
	= link_to (t'.edit_picture'), edit_picture_path(@picture), class: "btn btn-info"
	= link_to (t'.delete_picture'), picture_path(@picture), method: :delete, data: {confirm: "Are you sure deleted?"}, class: "btn btn-info"